name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Docker compose
      run: docker build . --file Dockerfile --tag luxwise/roomio_web_arq:$(date +%s)
          
